name: Package and upload to nuget.org

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Pack
        run: |
          dotnet pack .\src\My.Maui.Responsive\ --output .\output\ --configuration Release

      - name: Upload to nuget
        run: |
          dotnet nuget push .\output\*.nupkg `
            --source https://api.nuget.org/v3/index.json `
            --api-key ${{secrets.NUGET_API_KEY}} `
            --skip-duplicate true
        shell: pwsh
