name: Package and upload to nuget.org

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  package:
    runs-on: [windows-latest]

    steps:
      - name: Details
        run: |
          echo Event Name: ${{ github.event_name }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: |
          git fetch --prune --unshallow --tags
          git tag

      - name: Setup Gitversion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        if: github.event_name == 'push'
        run: |
          dotnet build `
            --configuration Release `
            /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} `
            /p:AssemblyFileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}
        shell: pwsh

      - name: Pack
        if: github.event_name == 'push'
        shell: pwsh
        run: |
          dotnet pack .\src\My.Maui.Responsive\ `
            --output .\output\ `
            --configuration Release `
            /p:Version=${{ steps.gitversion.outputs.fullSemVer }}

      - name: Upload to nuget
        if: github.event_name == 'push'
        shell: pwsh
        run: |
          dotnet nuget push .\output\*.nupkg `
            --source https://api.nuget.org/v3/index.json `
            --api-key ${{ secrets.NUGET_API_KEY }} `
            --skip-duplicate
