name: Run Tests

on: [push]

jobs:
  test:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build test projects
        shell: pwsh
        run: |
          dotnet build .\src\My.Maui.Responsive.Tests\ `
            --configuration Release

      - name: dotnet test
        shell: pwsh
        run: |
          dotnet test `
            --configuration Release `
            --no-build
